FROM python:3.11.2
WORKDIR /script
COPY script.py /
CMD [ "python", "/script.py" ]
# docker build -t scriptimage -f Dockerfile .
# docker rename scriptimage mascarar-dados
# docker run --name mascarar-dados -it scriptimage
